version: "2"

services:
  covina:
    build:
      context: .
    environment:
      DB: covina
      USER: ${INFLUXDB_ADMIN_USER}
      PASS: ${INFLUXDB_ADMIN_PASSWORD}
      SERVER: http://influxdb:8086
      DELAY: 60
    links:
        - influxdb

  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_READ_USER
      - INFLUXDB_READ_USER_PASSWORD
      - INFLUXDB_WRITE_USER
      - INFLUXDB_WRITE_USER_PASSWORD
      - INFLUXDB_HTTP_AUTH_ENABLED
      - INFLUXDB_DB=covina
      - INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD

  grafana:
    build:
      context: './grafana'
      args:
        INFLUXDB_DB: covina
        INFLUXDB_USER: ${INFLUXDB_READ_USER}
        INFLUXDB_PASSWORD: ${INFLUXDB_READ_USER_PASSWORD}    
    container_name: 'grafana'
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel
      - GF_AUTH_ANONYMOUS_ENABLED
      - GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD
