version: "2"

services:
  covina:
    build: .
    command: /app/covina -influx http://influxdb:8086
    links:
        - influxdb
  influxdb:
    image: influxdb
  grafana:
    build: './grafana'
    container_name: 'grafana'
    ports:
      - '127.0.0.1:3000:3000'
  # grafana:
  #   image: grafana/grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel