{
 "title": "Estimates",
 "time": { "from": "now/y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": "SHOW TAG  VALUES WITH KEY= \"country\""
   },
   { "name": "prevalence", "label": "Prevalence (%)", "query": "77" },
   { "name": "cfr", "label": "Selected CFR", "query": "0.53" }
  ]
 },
 "panels": [
  {
   "title": "Deaths ($country)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Observed",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid",
     "select": [
      [
       { "params": [ "sumDeaths" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    },
    {
     "alias": "0.4% CFR",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid",
     "select": [
      [
       { "params": [ "sumCases" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*0.004" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    },
    {
     "alias": "0.5% CFR",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid",
     "select": [
      [
       { "params": [ "sumCases" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*0.005" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    },
    {
     "alias": "0.75% CFR",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid",
     "select": [
      [
       { "params": [ "sumCases" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*0.0075" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    },
    {
     "alias": "1% CFR",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid",
     "select": [
      [
       { "params": [ "sumCases" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*0.01" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    },
    {
     "alias": "1.5% CFR",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "country" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "covid",
     "select": [
      [
       { "params": [ "sumCases" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*0.015" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Current CFR",
   "type": "stat",
   "description": "Current Case Fatality Ratio",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "covid",
     "query": "SELECT  (last(\"sumDeaths\")/last(\"sumCases\")) * 100 FROM \"covid\" WHERE (\"country\" =~ /^$country$/) AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "sumCases" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  },
  {
   "title": "Est. Fatalities",
   "type": "stat",
   "description": "Estimated fatalities at selected CFR and selected prevalence",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"population\")  *  ($prevalence/100)*($cfr/100) FROM \"covid\" WHERE (\"country\" =~ /^$country$/) AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 13 },
   "content": "\n# Fatalities estimation\n\nInsert `prevalence` and `CFR` (in percent) to calculate the cumulative falatilies for this country (defaults come from Institut Pasteur)\n\nNotes:\n- prevalence for seasonal flu is between 3% and 14%\n- COVID-19 spreads more rapidly; R0 is estimated to be at 3.3 without lockdown (yielding a 77% required prevalence to stop the spread)\n- CFR displayed here is over-estimated since not everyone is tested (CFR is presumed to be around 0.53%)\n\nRefs:\n  - https://ourworldindata.org/coronavirus\n  - https://www.who.int/docs/default-source/coronaviruse/who-china-joint-mission-on-covid-19-final-report.pdf\n  - https://www.pasteur.fr/fr/espace-presse/documents-presse/covid-19-modelisation-indique-que-pres-6-francais-ont-ete-infectes"
  },
  {
   "title": "Current prevalence",
   "type": "stat",
   "description": "Percentage of population affected by the virus",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "covid",
     "query": "SELECT  100*last(\"sumCases\")/last(\"population\") FROM \"covid\" WHERE (\"country\" =~ /^$country$/) AND $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "sumCases" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" }
     ]
    }
   ]
  }
 ]
}